/*
Sort:|0.09|
Question Type:|Geometry|
Question Name:|Loci - Point|
*/	

function locicircle(){var id=Math.random().toString(36).replace(/[^a-z]+/g,'').substr(0,20);x=randint(50,450);y=randint(50,250);size=randint(1,4);scale=randint(1,4);if(scale==4){scale=10}
if(scale==3){scale=5}
dist=size*scale;adj=randint(1,2);if(adj==1){scale+="km";dist+="km"}else{scale+="00m";dist+="00m"}
var question="<canvas id='"+id+"' width='500' height='300'>Canvas not supported</canvas><br>Size: <input id='slider"+id+"' type=range min=25 value=25 max=250 step=25 onchange='draw"+id+"()' oninput='draw"+id+"()'>";question+='<script>function draw'+id+'(){var canvas=document.getElementById("'+id+'");ctx = canvas.getContext("2d");ctx.clearRect(0,0,500,300);ctx.textAlign="left";ctx.font="12px Arial";ctx.fillText("Draw the Loci of all the points '+dist+' from the dot.",10,10);ctx.beginPath();ctx.moveTo(10,280);ctx.lineTo(10,290);ctx.lineTo(110,290);ctx.lineTo(110,280);ctx.moveTo(60,280);ctx.lineTo(60,290);ctx.stroke();ctx.textAlign="center";ctx.font="10px Arial";ctx.fillText("'+scale+'",35,288);ctx.fillText("'+scale+'",85,288);ctx.beginPath();ctx.arc("'+x+'","'+y+'",5,0,Math.PI*2,true);ctx.fill();ctx.beginPath();ctx.arc(targetX'+id+',targetY'+id+',document.getElementById("slider'+id+'").value,0,Math.PI*2,false);ctx.stroke();}var canvas'+id+'=document.getElementById("'+id+'"),ctx = canvas'+id+'.getContext("2d"),targetX'+id+' = 250,targetY'+id+' = 150;canvas'+id+'.width = 500; canvas'+id+'.height = 300;var flag'+id+' = 0;canvas'+id+'.addEventListener("mousedown", function(){flag'+id+' = 1;}, false);canvas'+id+'.addEventListener("mouseup", function(){flag'+id+' = 0;}, false);canvas'+id+'.addEventListener("mousemove", function(e){if(flag'+id+'==1){var rect = $("#'+id+'")[0].getBoundingClientRect();targetX'+id+' = e.clientX - rect.left;targetY'+id+' = e.clientY - rect.top;draw'+id+'();}});draw'+id+'();</script>';var answer='';var description='Position and size the circle appropriately.';var array={question:question,answer:answer,description:description,noworking:!0}
return array}