/*
Sort:|0.10|
Question Type:|Statistics|
Question Name:|Box and Whisker - Making a Call|
*/	

function ppdac9makeacall(){var type=randint(1,5);var a=randint(20,200);var b=randint(a+10,210);var c=randint(b+10,220);var d=randint(c+10,230);var e=randint(d+10,240);var f=randint(e+10,250);var g=randint(f+10,260);var h=randint(g+10,270);var i=randint(h+10,280);var j=randint(i+10,290);if(type==1){type='I can say back the population, Group B is bigger than Group A as none of their data overlaps';image='1='+a+'&2='+b+'&3='+c+'&4='+d+'&5='+e+'&6='+f+'&7='+g+'&8='+h+'&9='+i+'&10='+j+''}else if(type==2){type='I can say back the population, Group B is bigger than Group A as their boxes do not overlap';image='1='+a+'&2='+b+'&3='+c+'&4='+e+'&5='+h+'&6='+d+'&7='+f+'&8='+g+'&9='+i+'&10='+j+''}else if(type==3){type='I can say back the population, Group B is bigger than Group A as while their boxes touch, they do not overlap';image='1='+a+'&2='+b+'&3='+c+'&4='+e+'&5='+h+'&6='+d+'&7='+e+'&8='+f+'&9='+g+'&10='+j+''}else if(type==4){type='I can say back the population, Group B is bigger than Group A as both of the medians are outside the box of the other group';image='1='+a+'&2='+c+'&3='+d+'&4='+f+'&5='+i+'&6='+b+'&7='+e+'&8='+g+'&9='+h+'&10='+j+''}else{type="I don't have enough information to be able to tell if Group B is bigger than Group A in the population";image='1='+a+'&2='+c+'&3='+e+'&4='+g+'&5='+i+'&6='+b+'&7='+d+'&8='+f+'&9='+h+'&10='+j+''}
var question='<img src="https://www.jake4maths.com/generator/boxwhiskercompare.php?'+image+'"><br><select class=select answer="'+encode64(type)+'" style="max-width:90%">';question+='<option></option>';question+='<option>I can say back the population, Group B is bigger than Group A as none of their data overlaps</option>';question+='<option>I can say back the population, Group B is bigger than Group A as their boxes do not overlap</option>';question+='<option>I can say back the population, Group B is bigger than Group A as while their boxes touch, they do not overlap</option>';question+='<option>I can say back the population, Group B is bigger than Group A as both of the medians are outside the box of the other group</option>';question+="<option>I don't have enough information to be able to tell if Group B is bigger than Group A in the population</option>";question+='</select>';var answer='';var description="Select the correct call:"
var array={question:question,answer:answer,description:description}
return array}