/*
Sort:|0.10|
Question Type:|Statistics|
Question Name:|PPDAC - Eye Colour Problem, Plan and Data|
*/	

function ppdac3ppd(){var question='<div class=dropholder>'
question+='<b>Problem:</b><br>';question+=dragdropanswer('I wonder if')+'<br>';question+=dragdropanswer('students in our class')+'<br>';question+=dragdropanswer('are more likely to have blue or brown eyes?')+'<br><br>';question+='<b>Plan:</b><br>';question+=dragdropanswer('One student is going to go around the class')+'<br>';question+=dragdropanswer('and record what colour each student’s eyes are')+'<br>';question+=dragdropanswer('in a tally chart.')+'<br><br>';question+='<b>Data:</b><br>';question+='<table class=border><tr><td>Blue<td>Brown<td>Green<tr><td><s>||||</s> <s>||||</s> |||<td><s>||||</s> ||||<td>|||<tr>';question+='<td>'+dragdropanswer('13');question+='<td>'+dragdropanswer('9');question+='<td>'+dragdropanswer('3');question+='</table>';question+='</div>';question+='<div class=dragholder>';drops=[];drops.push('I wonder if');drops.push('students in our class');drops.push('are more likely to have blue or brown eyes?');drops.push('One student is going to go around the class');drops.push('and record what colour each student’s eyes are');drops.push('in a tally chart.');drops.push('13');drops.push('9');drops.push('3');drops=shuffle(drops);drops.forEach(function(entry){question+=dragdropdrops(entry)});question+='</div><style>.border td{border:1px solid #000;padding:2px;}.border{border-collapse:collapse;}</style>';var answer='Problem: I wonder if students in our class are more likely to have blue or brown eyes? Plan: One student is going to go around the class and record what colour each student’s eyes are in a tally chart.';var description="Drag and drop to put the words into the correct place:"
var array={question:question,answer:answer,description:description}
return array}